version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: help_bridge_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: help_bridge
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  help-bridge-app:
    build: .
    container_name: help_bridge_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/help_bridge
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - postgres-db

volumes:
  postgres_data: