
#-- Postgres Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/help_bridge
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

#-- JPA Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false